### ISSUE TITLE
Support for "require-types"

### ISSUE THREAD

**Issue by ceilfors** [tclindner/npm-package-json-lint#109]
This is not from the official package.json, but from TypeScript. See: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

Notice that `typings` is a synonym, so supporting `require-typings` would be nice too.

**Comment by tclindner** [comment]
Cool. 😎 I'm up for adding this.

**Comment by tclindner** [comment]
Hey @ceilfors - Let me know if you have any issues. 
https://github.com/tclindner/npm-package-json-lint/releases/tag/v3.7.0

**Comment by ceilfors** [comment]
Thanks for adding this!
