### ISSUE TITLE
Website not updated

### ISSUE THREAD

**Issue by regseb** [tclindner/npm-package-json-lint#1164]
The website doesn't have the latest [_v7.1.0_](https://github.com/tclindner/npm-package-json-lint/releases/tag/v7.1.0) version of npm-package-json-lint. There are no [new `type` rules](https://github.com/tclindner/npm-package-json-lint/pull/1087) in the [_Rules_](https://npmpackagejsonlint.org/docs/rules/) page. And the [`require-type`](https://npmpackagejsonlint.org/docs/rules/required-node/require-type), [`type-type`](https://npmpackagejsonlint.org/docs/rules/type/type-type) and [`valid-values-type`](https://npmpackagejsonlint.org/docs/rules/valid-values/valid-values-type) pages don't exist.

**Comment by tclindner** [comment]
Sorry about that! This should be fixed. There was a bug with the mdx compile after the docusaurus v3 upgrade and the hosting environment needed to be updated to node 18!
