### ISSUE TITLE
No configuration found when installed with pnpm

### ISSUE THREAD

**Issue by cdfa** [tclindner/npm-package-json-lint#124]
I installed `npm-package-json-lint-config-default` and created the config file from it's installation instructions, but it says it can't find the config. When pointing it to the config with `-c .npmpackagejsonlintrc.json` it does work.

When reporting a bug, please include:

  * A little info about your environment
    * npm-package-json-lint version: `2.0.0`
    * ~npm version:~ pnpm version: `3.6.1`
    * node version: `v10.15.3`
  * The output from npm-package-json-lint:
```
$ npx npmPkgJsonLint .
No npm-package-json-lint configuration found.
./package.json
```
  * What you expected to happen
`package.json` gets checked.

**Comment by tclindner** [comment]
Hey @cdfa! Sorry you are having issues. Can you please clarify a few things for me?

1.  You are running `3.6.1` of `npm-package-json-lint` and `2.0.0` of `npm-package-json-lint-config-default`?
2. Is `npm-package-json-lint` installed as a `devDependency` or `dependency` in your project?
3. Where is your `.npmpackagejsonlintrc.json` config file located?

**Comment by cdfa** [comment]
Wow you reply quick!
1. Oops, `2.0.0` of `npm-package-json-lint-config-default` indeed, but `3.7.0` of `npm-package-json-lint`. The `3.6.1` is from the package manager i use: [PNPM](https://pnpm.js.org/). It deduplicates packages system-wide using a lot of linking, but I don't think that's the issue here, since it doesn't seem to have any problem reading the config from the package when it has the `.npmpackagejsonlintrc.json`.
2. Yup
3. In the project root

**Comment by tclindner** [comment]
Thank you for confirming! Sorry for all of the questions. Do you know where `npm-package-json-lint` gets installed for the project you are using when you are using `pnpm`? Right now it currently walks the directory structure up from the place it is installed. If it can't find anything then it checks your home directory. Finally, it checks for for any cli passed paths. 

I tried running `npx npmPkgJsonLint .` in a few of my repos and it is picking up the config (from extends). I'm curious if `pnpm` is installing it outside of the directory structure your project is in. Maybe a central location based on the docs you linked to?

**Comment by cdfa** [comment]
Ah! That makes sense then.`pnpm` installs all packages in a central location in the home directory, so if `npm-package-json-lint` walks up from there it won't find my project's config.

I think that behaviour is quite unexpected though. I would expect to at least have it start from current working directory instead of it's install location.

**Comment by tclindner** [comment]
Yep, I agree! I’m working on adjusting how this works in v4. If you don’t mind running a beta, you can give v4 a try by installing `npm-package-json-lint@beta`. If you would prefer not to use a beta, would you be comfortable using the `-c` flag until v4 is ready?

**Comment by cdfa** [comment]
Yeah using the `-c` flag is just fine! Good to know the root cause of the issue and that it will be resolved soon!
