### ISSUE TITLE
Enhancement: `prefer-no-dependencies` rules

### ISSUE THREAD

**Issue by simison** [tclindner/npm-package-json-lint#132]
Hello! :wave: 

I'd have a use case for `prefer-no-devDependencies` rule. :-)

In a [monorepo](https://github.com/Automattic/wp-calypso/) managed by [Lerna](https://github.com/lerna/lerna) that is configured in a specific way, all `devDependencies` should go to root `package.json` or they won't get installed at all.

Therefore I'd like to verify that `devDependencies` are not added to monorepo's `package.json` files.

**Comment by tclindner** [comment]
Hey @simison - Thank you so much for adding this 🙌
