### ISSUE TITLE
No configuration found error with 4.0.0

### ISSUE THREAD

**Issue by ntwb** [tclindner/npm-package-json-lint#140]
Looking at the Greenkeeper PR https://github.com/WordPress-Coding-Standards/stylelint-config-wordpress/pull/242

Travis CI build is failing with the following error:
```
> npmPkgJsonLint .

No npm-package-json-lint configuration found.

There has been no recent changes to my `npmPackageJsonLintConfig` config:
/home/travis/build/WordPress-Coding-Standards/stylelint-config-wordpress/package.json
```

https://github.com/WordPress-Coding-Standards/stylelint-config-wordpress/blob/master/package.json#L97-L107

I suspect this issue is related to the addition of cosmiconfig?

**Comment by tclindner** [comment]
Hey @ntwb! Yeah, I think you are right. Can you please try updating your package.json property to `npmpackagejsonlint`? I'll get the docs updated to reflect that (sorry about missing that). 

Thank you! 🤞

**Comment by ntwb** [comment]
Thanks, that worked 🎉
