### ISSUE TITLE
Array type rules now ensure at least one item is passed - contradicts prefer-property-order options

### ISSUE THREAD

**Issue by sakthivel-tw** [tclindner/npm-package-json-lint#142]
**Issue Description**

Release notes for `npm-package-json-lint` v4.0.0 states: `Array type rules now ensure at least one item is passed`.

This contradicts to the rule `prefer-property-order` which can allow empty array.

https://npmpackagejsonlint.org/docs/en/rules/package-json-properties/prefer-property-order

  * A little info about your environment
    * npm-package-json-lint version - **v4.0.0**
    * npm version
    * node version - **node:10.16**
  * The output from `npm-package-json-lint`
```
cli:
	Configuration for rule "prefer-property-order" is invalid:
	- the second item in an array rule config must have at least 1 item.
```

  * What you expected to happen
    * Should accept empty array as per the documentation: https://npmpackagejsonlint.org/docs/en/rules/package-json-properties/prefer-property-order
  * The steps to reproduce the problem
```
{
  "rules": {
    "prefer-property-order": ["error", []]
  }
}
```

**Comment by tclindner** [comment]
Good catch, @sakthivel-tw 🙌

**Comment by tclindner** [comment]
@sakthivel-tw let me know if you still have issues!

**Comment by sakthivel-tw** [comment]
Thanks for the fix!
