### ISSUE TITLE
globby does not find package.json files under windows

### ISSUE THREAD

**Issue by mhohmeier** [tclindner/npm-package-json-lint#152]
Hi!
Since Version 10.0.0, globby only allows forward slashes in patterns. This can be found here:
[https://github.com/sindresorhus/globby/releases/tag/v10.0.0](https://github.com/sindresorhus/globby/releases/tag/v10.0.0) and here
[https://github.com/mrmlnc/fast-glob/releases/tag/3.0.0](https://github.com/mrmlnc/fast-glob/releases/tag/3.0.0)

getFileList.js in this repository uses path.sep which is "\\" on Windows.
This leads to globby not finding any package.json file, and therefore no package.json file being linted on Windows.

I suggest replacing all '\\' path separators with '/'. In fact i tried making  a pull request myself but your lint tests also rely on forward slasehd (i.e. getIgnorer.test.js, l. 66).

Or am i missing something?

Thanks!

**Comment by tclindner** [comment]
Hey @mhohmeier! Sorry about that. I didn't catch the path separator change in `fast-glob` (dep of globby). I've released v4.0.5. All `path.sep` instances have been replaced with `/`. Please let me know if you have additional issues.
