### ISSUE TITLE
Add prefer-alphabetical-scripts rule

### ISSUE THREAD

**Issue by aaroncadrian** [tclindner/npm-package-json-lint#153]
This rule would function similarly to `prefer-alphabetical-dependencies` and `prefer-alphabetical-devDependencies` on the keys of `scripts`.

**Comment by tclindner** [comment]
Hey @aaroncadrian [`v4.2.0`](https://github.com/tclindner/npm-package-json-lint/releases/tag/v4.2.0) has been released. Let me know what you think of the new rule!
