### ISSUE TITLE
Add no-types-in-dependencies rule

### ISSUE THREAD

**Issue by aaroncadrian** [tclindner/npm-package-json-lint#154]
I'd like a rule that forbids `@type/*` dependencies from appearing in `dependencies`.  By my standards, all `@type/*` dependencies should appear only in `devDependencies`.  I'd like a rule to enforce this.

**Comment by tclindner** [comment]
Hey @aaroncadrian thank you for using npm-package-json-lint!! What do you think about using [`no-restricted-dependencies`](https://npmpackagejsonlint.org/docs/en/rules/dependencies/no-restricted-dependencies) to accomplish this? It will require all `@types/*` to be listed. Let me know if that seems unmanageable and we can discuss further.

**Comment by aaroncadrian** [comment]
No problem! Thanks for all your hard work, @tclindner!

I like this approach with `no-restricted-dependencies` since it’s much more flexible. Could you make it possible for the rule to accept a list of regular expressions? That way instead of listing each `@types/*` dependency, I can just put `@types/.*`. 

The idea is that I’d want this linter to make my build pipeline fail, so I need a way to capture dependencies that I don’t know about yet before it’s too late.

**Comment by tclindner** [comment]
Yeah, that’s a great idea! I can take a stab at the implementation.

**Comment by tclindner** [comment]
Hey @aaroncadrian [`v4.2.0`](https://github.com/tclindner/npm-package-json-lint/releases/tag/v4.2.0) has been released. Let me know what you think of the enhanced rules!

**Comment by aaroncadrian** [comment]
Fantastic work! Thank you so much!
