### ISSUE TITLE
Add no-repeated-dependencies rule

### ISSUE THREAD

**Issue by aaroncadrian** [tclindner/npm-package-json-lint#155]
On one of my projects, someone installed a dependency in `dependencies` that already existed in `devDependencies`.

For example:

```
{
  "dependencies": {
    "a": "^1.0.0",
    "b": "^1.0.0"
  },
  "devDependencies": {
    "b": "^1.0.0",
    "c": "^1.0.0"
  }
}
```

In this example, I'd like a rule that would throw an error upon detecting that `b` is in both `dependencies` and `devDependencies`.

**Comment by tclindner** [comment]
Hey @aaroncadrian [`v4.2.0`](https://github.com/tclindner/npm-package-json-lint/releases/tag/v4.2.0) has been released. Let me know what you think of the new rule!
