### ISSUE TITLE
empty description results in javascript error

### ISSUE THREAD

**Issue by tomtomsen** [tclindner/npm-package-json-lint#163]
# Description
If there is a empty description in `package.json`, `npm-package-json-lint` fails with the error `Cannot read property 'toUpperCase' of undefined`.

# Environment:
- `npm-package-json-lint`: `4.1.0`
- `npm`: `6.13.0`
- `node`: `10.16.3`

# My `package.json`:
```json
{
   ...
   description: "",
   ...
}
```

# Output:
```shell
# ./node_modules/.bin/npmPkgJsonLint -c .npmpackagejsonlintrc.json .     
Cannot read property 'toUpperCase' of undefined
```

# Expected:
List of all actual errors

**Comment by tclindner** [comment]
Hey @tomtomsen! Nice catch! I’ll get a release cut tomorrow with your fix. Thank you for opening a PR 🙌

**Comment by tclindner** [comment]
Hey @tomtomsen, [`v4.1.1`](https://github.com/tclindner/npm-package-json-lint/releases/tag/v4.1.1) has been released. Thank you again for fixing this issue 🥇
