### ISSUE TITLE
Allow specifying values for private

### ISSUE THREAD

**Issue by joefiorini** [tclindner/npm-package-json-lint#19]
We have a monorepo for our engineering team. We have a setup inspired by `babel`, `react` and others, where lots of npm packages live in a single repo. For all of those, we need to ensure that `private` is always set to true in the `package.json`. Is this something this tool could do?

**Comment by tclindner** [comment]
Yeah! Do you think the following will meet your needs? If so, I'll create a new release this weekend.

Create a new rule name: prefer-private-as-true


Enabling this rule will result in an error being generated if `private` is missing or is set to false.

## Example .npmpackagejsonlintrc configuration

```json
{
  "prefer-private-as-true": "error"
}
```

## Rule Details

### *Incorrect* example(s)

```json
{
}
```

```json
{
  "private": false
}
```

### *Correct* example(s)

```json
{
  "private": true
}
```

**Comment by tclindner** [comment]
@joefiorini npm-package-json-lint currently has a rule, valid-values-private, that isn't as specific as the proposed rule above, but it scales for users that prefer false. Would you be okay using it instead of creating a new rule? Here is a link to the rule documentation - https://github.com/tclindner/npm-package-json-lint/wiki/valid-values-private. Let me know what you think. Thanks!

**Comment by joefiorini** [comment]
@tclindner I'm so sorry, what I actually meant to say here was allowed values for the `license` property. That way we can ensure that packages are `private` and `unlicensed` (which is the npm recommendation for private packages).

**Comment by tclindner** [comment]
@joefiorini sorry for misunderstanding! Your idea is great! That sounds like a perfect enhancement for this project. Do you think the following rule will meet your needs?

Create a new rule named: `valid-values-license`

Enabling this rule will result in an error being generated if license is not equal to one of the values in the array of valid values.

## Example .npmpackagejsonlintrc configuration

```json
{
  "valid-values-license": ["error", [
    "private",
    "unlicensed"
  ]]
}
```

## Rule Details

### *Incorrect* example(s)

```json
{
  "license": "MIT"
}
```

### *Correct* example(s)

```json
{
  "license": "private"
}
```

```json
{
  "license": "unlicensed"
}
```

**Comment by joefiorini** [comment]
@tclindner that looks perfect! thanks for the quick reply!

**Comment by tclindner** [comment]
No problem, @joefiorini. I'll get a new release cut this weekend. Thank you!

**Comment by tclindner** [comment]
@joefiorini v1.4.0 has been released! Please let me if it doesn't work for you. I would love to add any additional features you and your team are interested in.

**Comment by joefiorini** [comment]
@tclindner Thanks a lot!
