### ISSUE TITLE
forbidEndingPeriod

### ISSUE THREAD

**Issue by piranna** [tclindner/npm-package-json-lint#196]
https://github.com/tclindner/npm-package-json-lint/blob/b3233087c719dbcaf8353f06b9971539f48df490/src/rules/description-format.js#L33

The same that there's a `requireEndingPeriod` option, add a new one for `forbidEndingPeriod`, or allow it to be three state.

**Comment by tclindner** [comment]
I like it! Thanks for the suggestion. I’ll take a stab when I review the other ticket you commented on.

**Comment by piranna** [comment]
Nice! :-D

**Comment by tclindner** [comment]
v4.6.0 has been released with the new option. I'll consolidate them in v5.0.0 (breaking change).

**Comment by piranna** [comment]
Cool, thanks! :-D
