### ISSUE TITLE
Feature request: scripts must contain ['test', 'lint', ...]

### ISSUE THREAD

**Issue by almeynman** [tclindner/npm-package-json-lint#227]
Hi, thanks for this awesome package!

We have a monorepo and most of the packages have similar scripts (lint, test, etc.), so we wanted to enforce the same naming convention for common scripts. I am willing to do a PR on it, however I have not found any rule like that, i.e. that accepts an array of strings. Could you direct me on how to implement it?

**Comment by tclindner** [comment]
Hey @almeynman! Thank you for using the package and for offering to add a new feature 🎉 

You can model the new rule after `prefer-property-order`. Here is a link to the [source file](https://github.com/tclindner/npm-package-json-lint/blob/master/src/rules/prefer-property-order.js) and the [test file](https://github.com/tclindner/npm-package-json-lint/blob/master/test/unit/rules/prefer-property-order.test.js). 

Here are some notes:

* Please add validators in the validator directory. Ex: `const {isInPreferredOrder} = require('./../validators/property-order');`
* Please require the common lint issue object. `const LintIssue = require('./../LintIssue');`
* 
```
const {isInPreferredOrder} = require('./../validators/property-order'); // Please add validators in the validator directory, if applicable
const LintIssue = require('./../LintIssue'); // Please use the shared lint issue object

const lintId = 'prefer-property-order'; // this is the name of the rule. 
const nodeName = ''; // this should be scripts
const message = 'Your package.json properties are not in the desired order.'; // error message if the rule is tripped. 
const ruleType = 'array'; // you will want to keep this set to array
const minItems = 0; // minimum number of items the array much contain.
 
// the lint function will always receive the package.json data as an object first
// severity as a string second
// array rules will get the array from the config object third. You can rename `preferredOrder` to `requiredScripts` or whatever you want to name it. 
const lint = (packageJsonData, severity, preferredOrder) => {
  const result = isInPreferredOrder(packageJsonData, preferredOrder);
  if (!result.status) {
    return new LintIssue(lintId, severity, nodeName, `${message} ${result.msg}`);
  }
  return true;
};

// keep the exports the same
module.exports = {
  lint,
  ruleType,
  minItems
};
```

What do you think for the rule name (lintId)? I would like to place it in the [`scripts` section of the docs](https://npmpackagejsonlint.org/docs/en/rules#scripts-rules).

Speaking of docs you can add them here - https://github.com/tclindner/npm-package-json-lint/tree/master/docs/rules/scripts

**Comment by almeynman** [comment]
Hey @tclindner, The priorities have shifted a bit and I am not sure when I will be able to tackle this feature. I have added it to the backlog, but will not be able to work on it this week for sure. So feel free to implement it, I will be able to test and give feedback

**Comment by tclindner** [comment]
Hey @almeynman `v5.1.0` is now available! Here's a link to the docs. Hopefully it works well for you.

https://npmpackagejsonlint.org/docs/en/rules/scripts/prefer-scripts

**Comment by almeynman** [comment]
@tclindner Thank you, works as expected
