### ISSUE TITLE
Exit with non zero code if error found

### ISSUE THREAD

**Issue by evilebottnawi** [tclindner/npm-package-json-lint#25]
I can do PR if your accept.

**Comment by tclindner** [comment]
Hi @evilebottnawi! Thanks for posting the issue and offering to post a PR. Your suggestion makes sense. I'll accept the PR if you have time. No worries if you don't. I can get it updated this weekend.

**Comment by tclindner** [comment]
Hi @evilebottnawi let me know if v2.1.0 meets your expectations. Let me know if there are any other changes or enhancements that you would like! Thanks again for logging the issue.

**Comment by evilebottnawi** [comment]
@tclindner works good, but if i have warning i got non zero error code, but warning it is not error and should be non zero exit code.

**Comment by tclindner** [comment]
Good call. I'll get a fix pushed out that ensures the exit code is 0 if only warning are detected.

**Comment by tclindner** [comment]
v2.1.1 has been published.
