### ISSUE TITLE
Some rules not respected configuration

### ISSUE THREAD

**Issue by evilebottnawi** [tclindner/npm-package-json-lint#27]
I have config for some rules:
```json
{
    "rules": {
        "valid-values-author": "off",
        "valid-values-private": "off",
        "valid-values-license": "off"
    }
}
```
But I still get a output about a warning:
```shell
----warnings-----
valid-values-author - node: author - Invalid value for author
valid-values-private - node: private - Invalid value for private
valid-values-license - node: license - Invalid value for license
```

**Comment by tclindner** [comment]
Hey @evilebottnawi! Thank you again for logging a ticket. You found a good one 👍 valid-value-* rules are part of array style rules (ex: below). 

```
"valid-values-author": ["error", [
  "Thomas",
  "Thomas Lindner"  
]]
```

When I was adding the ability to turn rules off I only accounted for updating the severity in the array form (see following example).
```
"valid-values-author": ["off", [
  "Thomas",
  "Thomas Lindner"  
]]
```

Your example configuration above is an excellent improvement that makes turning this type of rule off much easier. I'll release a new version and add a new unit test.
```
"valid-values-author": "off"
```

Thank you again! Let me know if you find additional issues and/or have features you would like added.

**Comment by tclindner** [comment]
v2.1.2 has been released. I've updated the documentation to ensure others know how to use the new method of disabling the rules. Ex: https://github.com/tclindner/npm-package-json-lint/wiki/valid-values-author

Let me know if you have suggestions. Thanks again!

**Comment by evilebottnawi** [comment]
@tclindner Thanks!
