### ISSUE TITLE
Reduce package size

### ISSUE THREAD

**Issue by evilebottnawi** [tclindner/npm-package-json-lint#31]
Package contains unnecessary directories and files - `grunt`, `tests`, `.jscsrc` and maybe others. I can do PR if your accept this issue.

**Comment by tclindner** [comment]
Yeah, I definitely will accept this change! Are you thinking about adding the files and directories to the `.npmignore` file?

**Comment by evilebottnawi** [comment]
@tclindner I personally use `files`, if you forget to add a file just release the patch version, because it's hard to get around all the files through `.npmignore`

**Comment by tclindner** [comment]
That sounds great to me! Thank you for helping improve this tool 🥇

**Comment by tclindner** [comment]
Let me know what you think about v2.3.0, @evilebottnawi! grunt, tests, and other dot files should no longer be in the package.

**Comment by evilebottnawi** [comment]
@tclindner all fine :+1:
