### ISSUE TITLE
Rule idea - alphabet sorting for dependencies, devDependencies and etc

### ISSUE THREAD

**Issue by evilebottnawi** [tclindner/npm-package-json-lint#33]

**Comment by tclindner** [comment]
Great suggestion, @evilebottnawi! I'll start working on the rules tomorrow.

**Comment by tclindner** [comment]
Hey @evilebottnawi!

Here are the links to the new rules. Let me know if they meet your expectations.

- [prefer-alphabetical-dependencies](https://github.com/tclindner/npm-package-json-lint/wiki/prefer-alphabetical-dependencies)
- [prefer-alphabetical-devDependencies](https://github.com/tclindner/npm-package-json-lint/wiki/prefer-alphabetical-devDependencies)
- [prefer-alphabetical-bundledDependencies](https://github.com/tclindner/npm-package-json-lint/wiki/prefer-alphabetical-bundledDependencies)
- [prefer-alphabetical-optionalDependencies](https://github.com/tclindner/npm-package-json-lint/wiki/prefer-alphabetical-optionalDependencies)
- [prefer-alphabetical-peerDependencies](https://github.com/tclindner/npm-package-json-lint/wiki/prefer-alphabetical-peerDependencies)

**Comment by evilebottnawi** [comment]
@tclindner thanks, starting integrate :smile:

**Comment by evilebottnawi** [comment]
@tclindner Everything works almost perfectly, but:
Be good to improve UX error.
Now we have 
```shell
prefer-alphabetical-devDependencies - node: devDependencies - Your devDependencies are not in alphabetical order. Please update the order.
```
But if i have a lot of deps it is rather difficult to determine what is incorrectly sorted. Maybe:
```shell
prefer-alphabetical-devDependencies - node: devDependencies - Your devDependencies are not in alphabetical order. Please update the order. `apackage` package should be before `bpackage`
```
Or something in kind style :smile: 

Also your can see https://github.com/yarnpkg/yarn/blob/master/src/util/normalize-manifest/fix.js what `yarn` fix in `package.json` automatically and get inspired for new rules.

**Comment by evilebottnawi** [comment]
I can add that I do not quite agree with the work of yarn when it automatically corrects errors, because in fact I myself must manage the process as I want to see my package.json

**Comment by tclindner** [comment]
@evilebottnawi great suggestion! I'll reopen this and push an improvement soon.

**Comment by tclindner** [comment]
I plan on releasing the UX improvement tomorrow with v2.4.0. Thank you @evilebottnawi. Let me know if you have any other suggestions!
