### ISSUE TITLE
Rule for validation `package.json` agains schema.

### ISSUE THREAD

**Issue by evilebottnawi** [tclindner/npm-package-json-lint#40]

**Comment by tclindner** [comment]
Hi @evilebottnawi can you provide a bit more detail around this request? I apologize, but I want to ensure I get you what you are looking for. Thank you!!

**Comment by evilebottnawi** [comment]
@tclindner Seems like this https://gist.github.com/evilebottnawi/ef2a8a89be52c8578d92af2007dc5076, maybe it is not rule, build-in linter before run rules.

**Comment by tclindner** [comment]
Thanks @evilebottnawi. I see what you mean now. How do you see consumers using the schema? The schema file is pretty large and users could easily misconfigure it.

**Comment by tclindner** [comment]
Removing this from 2.5.0 since it will not be ready for release today.

**Comment by evilebottnawi** [comment]
@tclindner it is be just idea :+1:

**Comment by tclindner** [comment]
Hi @evilebottnawi I think I'm going to hold on this ask for now. Specifying a schema is more difficult to ask a user to do. Are you comfortable with that? 

I would like your opinion on a couple of alternative features. I was thinking about adding an `--init` option to the CLI. Hopefully this will make it easier to get started. I've also been considering a UI that can be used to generate a config object. What do you think?

**Comment by evilebottnawi** [comment]
@tclindner sound good :+1:

**Comment by tclindner** [comment]
Thank you!
