### ISSUE TITLE
Use https://github.com/davidtheclark/cosmiconfig for configuration files

### ISSUE THREAD

**Issue by evilebottnawi** [tclindner/npm-package-json-lint#43]
It is allow many formats for configuration files :+1:

**Comment by tclindner** [comment]
Very cool! @evilebottnawi do you have any formats that you want implemented more than another?

**Comment by evilebottnawi** [comment]
@tclindner no :smile: These formats is enough in 99.99% case

**Comment by tclindner** [comment]
Hey @evilebottnawi I've been trying to keep the number of dependencies down. I was able to add support for a property in the package.json file, a JavaScript export (npmpackagejsonlint.config.js), and optional extension support for the rc file without a ton of code. The cli will also automatically look for `.npmpackagejsonlintrc` and `npmpackagejsonlint.config.js` in the current working directory if the `-c` option isn't provided. If nothing is found it falls back to looking for global config in the user directory. I didn't add yaml support. Let me know what you think. I'm hopeful this will get you nearly everything you were looking for. 

Thank you!

**Comment by evilebottnawi** [comment]
@tclindner I think support `.npmpackagejsonlintrc` and `npmpackagejsonlint.config.js` is enough, thanks! YAML is rarely used for configuration, so your can think about it when your take request to support it.

**Comment by tclindner** [comment]
Perfect! Thank you
