### ISSUE TITLE
Support for eslint-plugin?

### ISSUE THREAD

**Issue by moshest** [tclindner/npm-package-json-lint#47]
I think this module could be use as a eslint-plugin.

Please see [eslint-plugin-json](https://www.npmjs.com/package/eslint-plugin-json) for reference (this plugin linting json files).

**Comment by tclindner** [comment]
Hey @moshest - thank you for logging this request! Are you thinking that npm-package-json-lint would run as part of a user's ESLint check? What do you see as the biggest advantage of this feature?

**Comment by moshest** [comment]
Please check the tool [Lerna](https://github.com/lerna/lerna). It's a library that helps users write multi-module projects like [Babel](https://github.com/babel/babel), [React.js](https://github.com/facebook/react) and more..

Adding ESLinting support for those project could be very convenient.

**Comment by tclindner** [comment]
Hi @moshest sorry if I'm slow, but I would like to make sure I understand what you would like. 🤓

You would like:

1. support for projects that use Lerna to generate multiple packages?
2. support for running npm-package-json-lint via ESLint

Thank you for the interest in the project!

**Comment by moshest** [comment]
I'm just saying that create this library as eslint plugin could be very helpful for projects with multiple packages.

There is no need for custom support for Lerna projects. The plugin can do it automatically by es-linting every `package.json` file just like the plugin [eslint-plugin-json](https://www.npmjs.com/package/eslint-plugin-json) linting every `*.json` file.

**Comment by tclindner** [comment]
Hey @moshest - a pre-release of v3.0.0 has been published to npm. The documentation is still a little sparse (that will change by the stable release). You can try it out by installing `npm-package-json-lint@beta`. Here is a link to the start of the [migration guide](https://github.com/tclindner/npm-package-json-lint/wiki/migrating-from-v2-to-v3). Do you think this will meet your needs for lerna projects?

Let me know what you think!

**Comment by moshest** [comment]
For my Lerna project i just wrote a script that lint every module. You can find it here: https://github.com/remotelib/remote-lib/blob/master/scripts/lint-package.sh

I think that the main feature here is the eslint framework support.

**Comment by ntwb** [comment]
I went and took a look at the feasibility of converting the rules here into ESLInt rules and I don't believe this is possible primarily because ESLint does **not** include a JSON parser and has no plan of doing so. 

Also `eslint-plugin-json` is **not** extensible with any rules or configs, it only checks that JSON files are valid, that is it.

**Comment by moshest** [comment]
Just to clarify, we looking for a JSON parser that can return a `line` and a `column` map for every property on the JSON file. Right?

**Comment by tclindner** [comment]
Thank you so much for digging in to this, @ntwb! @moshest yeah, that would be great. I haven't found an active project to parse JSON files to AST. Are you aware of anything?

**Comment by tclindner** [comment]
Hey @moshest and @ntwb - have you two found a good option for parsing JSON files to AST? I haven't had much luck finding anything.

**Comment by tclindner** [comment]
Closing based on discussion with @ntwb. Relates to #81. 
https://github.com/tclindner/npm-package-json-lint/issues/81#issuecomment-508659251
