### ISSUE TITLE
Support for entires order?

### ISSUE THREAD

**Issue by moshest** [tclindner/npm-package-json-lint#50]
I wonder if there is support for entries ordering such as: First `name` then `description` etc..

I would like it to have default ordering and if I want I can reorder it by given an array of entries.

**Comment by tclindner** [comment]
Hey @moshest that isn't currently an option, but I think it is a great idea. I'll mark this issue as an enhancement and work on it as soon as I can!

**Comment by tclindner** [comment]
Hey @moshest thank you for the suggestion. v2.8.0 has been released with a new rule named `prefer-property-order`. Here is a [link to the documentation](https://github.com/tclindner/npm-package-json-lint/wiki/prefer-property-order). Let me know what you think.

**Comment by moshest** [comment]
Great!

I think that providing a default order for this role can help many users:

```js
[
    'name',
    'version',
    'description',
    'keywords',
    'homepage',
    'bugs',
    'license',
    'author',
    'contributors',
    'files',
    'main',
    'module',
    'jsnext:main',
    'types',
    'typings',
    'style',
    'example',
    'examplestyle',
    'assets',
    'bin',
    'man',
    'directories',
    'repository',
    'scripts',
    'config',
    'pre-commit',
    'browser',
    'browserify',
    'babel',
    'eslintConfig',
    'stylelint',
    'dependencies',
    'devDependencies',
    'peerDependencies',
    'bundledDependencies',
    'bundleDependencies',
    'optionalDependencies',
    'engines',
    'engineStrict',
    'os',
    'cpu',
    'preferGlobal',
    'private',
    'publishConfig',
]
```

(Copied from [sort-package-json](https://www.npmjs.com/package/sort-package-json) module)

 We also need to check that entries that missing from the `package.json` file but exists on the `order` list would not reject as an error.

For example:

```json
{
  "rules": {
    "prefer-property-order": ["error", [
      "name",
      "version",
      "description"
    ]]
  }
}
```

Valid `package.json`:
```json
{
  "name": "npm-package-json-lint",
  "description": "CLI app for linting package.json files."
}
```

Invalid `package.json`:
```json
{
  "description": "CLI app for linting package.json files.",
  "name": "npm-package-json-lint"
}
```

**Comment by tclindner** [comment]
Hi @moshest I've made these adjustments in v2.8.1. I updated [the documentation](https://github.com/tclindner/npm-package-json-lint/wiki/prefer-property-order) too. Let me know what you think.

**Comment by moshest** [comment]
Great! 🎉
