### ISSUE TITLE
Overrides broken when using CLI

### ISSUE THREAD

**Issue by dietergeerts** [tclindner/npm-package-json-lint#513]
Overrides are not being applied when using this through the CLI:

```
    "test": "cd .. && npmPkgJsonLint --noConfigFiles --configFile tools-lint-package-json-runner/npmpackagejsonlint.config.js ."
```

This should run the tool on all our packages. When I debug, I can see that when applying the overrides, the file to apply it to is the config. When further debugging, I can see that the code is functionally broken:

```
    if (typeof this.config === 'undefined') {
      debug(`User passed config is undefined.`);
      if (this.configFile) {
        debug(`Config file specified, loading it.`);
        config = cosmiconfigSync('npmpackagejsonlint', {
          transform: cosmicConfigTransformer.transform(this.cwd, this.configBaseDirectory, this.configFile),
        }).load(this.configFile);
      } else {
        debug(`Config file wasn't specified, searching for config.`);
        config = cosmiconfigSync('npmpackagejsonlint', {
          transform: cosmicConfigTransformer.transform(this.cwd, this.configBaseDirectory, filePathToSearch),
        }).search(filePathToSearch);
      }
    } else {
```
1. From CLI, `this.config` is indeed never provided.
2. `this.configFile` is provided, as I want a single config file to be used for all `package.json` files found, no local config file. _(the `--noConfigFiles has no effect btw)_
3. Transformation is thus done on the config file provided, meaning that it will never match any pattern, as the config file is a relative file path, while the pattern is changed to an absolute filepath.

Functionally, I would expect that the config is loaded first, and then having overrides being applied based on the loaded config and the file that needs to be linted, which is the correct functional way of doing it.

**Comment by dietergeerts** [comment]
When further debugging, I saw that there is no cwd passed to globby, meaning that overrides patterns aren't correctly matched if a custom cwd is being passed through the API.

**Comment by tclindner** [comment]
Hey @dietergeerts thank you for identifying this issue and for digging in to the cause. I'll release a fix passing `cwd` to `globby`. Let me know if that doesn't fix the issue.
