### ISSUE TITLE
Support for "require-module"?

### ISSUE THREAD

**Issue by moshest** [tclindner/npm-package-json-lint#52]
The [`module` property](https://github.com/dherman/defense-of-dot-js/blob/master/proposal.md)  is like the `main` property but for ES6 Import-Export modules.

**Comment by tclindner** [comment]
Hey @moshest is this officially supported? I don't see it in [npm's package.json documentation](https://docs.npmjs.com/files/package.json).

**Comment by moshest** [comment]
Module is been used by Rollup bundler.

You can see here: https://stackoverflow.com/a/42817320/518153
and here: https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c

**Comment by tclindner** [comment]
Thank you for the information, @moshest! Marking this as an enhancement.

**Comment by tclindner** [comment]
Hey @moshest - v2.11.0 has been released with this [rule](https://github.com/tclindner/npm-package-json-lint/wiki/require-module)! We can keep an eye on the proposal and adjust the rule, if needed!

**Comment by moshest** [comment]
Great!
