### ISSUE TITLE
Missing properties on `prefer-property-order` has unexpected behavour

### ISSUE THREAD

**Issue by moshest** [tclindner/npm-package-json-lint#57]
My package.json has the property `nyc` which is not included on the default order list at:

```json
{
  "rules": {
    "prefer-property-order": ["error", []]
  }
}
```

This rule is failing with the following error: 
```
Your package.json properties are not in the desired order. nyc is not in the preferred property list.
```

I think that `prefer-property-order` should ignore properties that are not in the preferred property list.

**Comment by tclindner** [comment]
Hey @moshest what is the purpose of the rule if we ignore properties that aren’t in the list? We are already allowing properties in the list to be missing from the package.json file.

**Comment by moshest** [comment]
Just ordering. Like the role `prefer-alphabetical-dependencies` which only check the order of the dependencies and not that in it.

The user should use other role to require properties.

**Comment by tclindner** [comment]
Gotcha. I see what you are thinking now. Thanks for talking that through, @moshest!

**Comment by tclindner** [comment]
Hi @moshest v2.10.0 has been released! Let me know if it meets your needs. Thank you for suggesting the great improvements.

**Comment by moshest** [comment]
Works great!
