### ISSUE TITLE
Types missing after upgrading from v5 to v6

### ISSUE THREAD

**Issue by xboy2012** [tclindner/npm-package-json-lint#593]
I found that after upgrading  from v5 to v6

the `index.d.ts` is deleted, the types are not exposed any more, which is also necessary when using the nodejs API.

Please add the missing types back.

https://github.com/tclindner/npm-package-json-lint/blob/9a0ef3f01960760922a5341f386c594a97c4d3e0/index.d.ts

**Comment by tclindner** [comment]
Hey @xboy2012 where you referencing this file directly? All types should be in the `dist` directory now. The package.json file has a types reference that points to the public api. Will this new approach work for you?

**Comment by xboy2012** [comment]
> Hey @xboy2012 where you referencing this file directly? All types should be in the `dist` directory now. The package.json file has a types reference that points to the public api. Will this new approach work for you?

These types are not exposed any more, which are necessary.

```
FileLintResult,
LinterResult,
LintIssue,
Severity,
NpmPackageJsonLintConfig
```

I believe these types are refactored into other places, but not exposed as before.

Currently in package.json `"types": "dist/src/api.d.ts",` indicate that only type `NpmPackageJsonLint` is exposed.

**Comment by tclindner** [comment]
Oops, sorry about that. I was thinking they were exported publicly. Let me know if you have any issues after 6.0.1 is released! Thanks @xboy2012
