### ISSUE TITLE
#595 release v6.0.2, please !

### ISSUE THREAD

**Issue by jschyz** [tclindner/npm-package-json-lint#596]
#595 release v6.0.2, please !

I need to use `LintIssue` API to implement some custom Rules。

```
const npmPackageJsonLint = new NpmPackageJsonLint({
  patterns: [root],
  configFile: path.resolve(__dirname, '../config/.npmpackagejsonlintrc.json')
});

npmPackageJsonLint.rules.registerRule([ruleId], [ruleIdPath])

const results = npmPackageJsonLint.lint();
```

The `ruleIdPath Module` lacks the LintIssue API

**Comment by jschyz** [comment]
![image](https://user-images.githubusercontent.com/3281438/157783364-84da51df-1327-45bd-8e62-71f3eea4d670.png)

`npm-package-json-lint.d.ts ` No type declaration

**Comment by tclindner** [comment]
Hey @jschyz thanks for calling this out. This was never a documented feature and was a private api. I will work tomorrow to try and get this exposed again. Sorry about that. I didn't realize you were using it like this! It is always fun to see what others are doing!

**Comment by jschyz** [comment]
I want to customize the extension rules，For example:

```
"lint-staged": {
    "**/*.less": "stylelint --syntax less",
    "**/*.{js,jsx,ts,tsx}": "npm run lint-staged:js",
    "**/*.{js,jsx,tsx,ts,less,md,json}": [
      "prettier --write"
    ]
},
"simple-git-hooks": {
    "pre-commit": "pnpm exec lint-staged --concurrent false",
    "commit-msg": "pnpm exec ts-node scripts/verifyCommit.ts $1"
  },
```

I want to check if the project has lint-staged, simply-Git-hooks attributes；to correct my team for proper execution；

so，want to add custom Rules

**Comment by jschyz** [comment]
![image](https://user-images.githubusercontent.com/3281438/157785215-e18734e9-e275-493c-9db1-b5963f4bba36.png)

I found it in the `api.d.ts` file

**Comment by tclindner** [comment]
Hey @jschyz please let me know if v6.0.2 works for you!
