### ISSUE TITLE
[Enhancement Request] Improve messaging for `no-restricted-dependencies`

### ISSUE THREAD

**Issue by pohnemus** [tclindner/npm-package-json-lint#610]
Hi - it would be wonderful if we could add more information to the error message for the `no-restricted-dependencies` rule. Right now it says "✖ no-restricted-dependencies - node: dependencies - You are using a restricted dependency. Please remove it." However on our team we use this to restrict many dependencies so users are struggling a bit knowing which dependency is the issue. What do you think about adding which dependencies are in conflict to the error message?

**Comment by tclindner** [comment]
Definitely! 🎉
