### ISSUE TITLE
More helpful default configuration

### ISSUE THREAD

**Issue by mcandre** [tclindner/npm-package-json-lint#63]
Ay, npm-package-json-lint should really report type screwups in package.json for any of the keys.

The `engine` presence check should also be enabled by default. It sucks when a Node.js project fails to document which version of Node.js is required to run it.

If `name` is missing, things are likely to break with npm. That should be on by default. Same goes for `version`.

**Comment by tclindner** [comment]
Hey @mcandre! Thank you for the feedback. I would love to improve the project so it meets your needs.  Do you currently use [npm-package-json-lint-config-default](https://github.com/tclindner/npm-package-json-lint-config-default) as your base/default configuration module to extend from?

**Comment by tclindner** [comment]
Hey @mcandre - Do you currently use [npm-package-json-lint-config-default](https://github.com/tclindner/npm-package-json-lint-config-default) as your base/default configuration module to extend from?

**Comment by tclindner** [comment]
Hey @mcandre I'm going to close this ticket. Let me know if [npm-package-json-lint-config-default](https://github.com/tclindner/npm-package-json-lint-config-default) doesn't meet your needs. I'd be happy to work with you to find a better solution.
