### ISSUE TITLE
Can't use an object as `author`with `valid-values-author`

### ISSUE THREAD

**Issue by hassankhan** [tclindner/npm-package-json-lint#64]
When reporting a bug, please include:

  * A little info about your environment
    * npm-package-json-lint version: 2.11.0
    * yarn version: 1.3.2
    * node version: 6.10.0
  * The output from npm-package-json-lint
```bash
1 error
✖ valid-values-author - node: author - Invalid value for author
```
  * What you expected to happen
No errors
  * The steps to reproduce the problem
Use a package.json with author like the following:
```json
author: {
  "name": "Joe Bloggs",
  "url": "https://example.com"
}
```

**Comment by tclindner** [comment]
Hey @hassankhan - Nice find! Thank you for reporting the issue. I'll target getting an update pushed out next week.

**Comment by tclindner** [comment]
Hi @hassankhan v2.11.1 has been released and the documentation has been updated. Let me know how this works for you.
