### ISSUE TITLE
name-scope-format & name-folder-format

### ISSUE THREAD

**Issue by RefinedSoftwareLLC** [tclindner/npm-package-json-lint#69]
Please add name-scope-format
Example: `@scope/name`
1) Forces `@scope/` to be before name
2) Forces scope and name to be lowercase

Please add name-folder-format

1) Require name to be the name of the folder that package.json is in
2) Require folder and name to be lowercase
3) Be compatible with name-scope-format (see above)

**Comment by tclindner** [comment]
Hi @RefinedSoftwareLLC - thank you for using this project! Thank you for suggesting new rules. I have a few questions about your request. 

`name-scope-format`

1. Would you be okay using `name-format` to validate that name is lowercase? Then both rules won't overlap in scope.
2. Are you okay with this rule validating that any scope is present? An alternative option would be to create a rule called `valid-values-name-scope`, where a list of valid values could be provided. What do you think?

`name-folder-format` 

Can you explain your use case for this rule?

**Comment by tclindner** [comment]
Hi @RefinedSoftwareLLC let me know what you think about the questions above.

**Comment by tclindner** [comment]
Hi @RefinedSoftwareLLC let me know what you think about the questions above.

**Comment by ntwb** [comment]
We at @WordPress are using [Lerna](https://github.com/lerna/lerna) and currently have [38 packages](https://github.com/WordPress/gutenberg/tree/master/packages) that are published to npmjs.com.


> Would you be okay using `name-format` to validate that name is lowercase? Then both rules won't overlap in scope.

This would work for our use case, also not just _lowercase_ it should also adhere to using _kebab-case_, as _snake_case_, _camelCase_, and _PascalCase_ are not valid npmjs.com URL formats etc.

> Are you okay with this rule validating that any scope is present? An alternative option would be to create a rule called `valid-values-name-scope`, where a list of valid values could be provided. What do you think?

Our use case would be that we would want to have the scope name `@wordpress` enforced, so the `valid-values-name-scope` rule would be great for us.
 
> `name-folder-format` Can you explain your use case for this rule?

All the packages that @WordPress has use the same folder name and package name (preceded with the `@wordpress` scope), so being able to have a rule that throws a warning _"Warning, the folder name and package name do not match"_ would be great.

**Comment by tclindner** [comment]
Thank you, @ntwb! I'll start in on this issue soon.

**Comment by tclindner** [comment]
Hey @RefinedSoftwareLLC I'm going to mark this complete based on the great work of @jogold 🙌 . Please let us know if you would like any further enhancements made!
