### ISSUE TITLE
bundledDependencies-type: should be an Array

### ISSUE THREAD

**Issue by akihyro** [tclindner/npm-package-json-lint#71]
"bundledDependencies" should be an **Array**.
But it is treated as an **Object**.

Quoted from the wiki page of "bundledDependencies-type":

> Enabling this rule will result in an error being generated if the value in bundledDependencies is not an object.
>
> https://github.com/tclindner/npm-package-json-lint/wiki/bundledDependencies-type

Quoted from the document page of package.json:

> **bundledDependencies**
>
> This defines an array of package names that will be bundled when publishing the package.
> 
> In cases where you need to preserve npm packages locally or have them available through a single file download, you can bundle the packages in a tarball file by specifying the package names in the bundledDependencies array and executing npm pack.
> 
> For example:
> 
> If we define a package.json like this:
> 
> ```json
> {
>   "name": "awesome-web-framework",
>   "version": "1.0.0",
>   "bundledDependencies": [
>     "renderized", "super-streams"
>   ]
> }
> ```
>
> https://docs.npmjs.com/files/package.json#bundleddependencies

- - -

### My environment

* npm-package-json-lint version: 2.11.1
* npm version: 5.6.0
* node version: 8.9.4

### The output from npm-package-json-lint

**package.json**

```json
{
    "bundledDependencies": [
        "foo",
        "bar"
    ]
}
```

**.npmpackagejsonlintrc**

```json
{
    "rules": {
        "bundledDependencies-type": "error"
    }
}
```

**Output**

```
1 error
✖ bundledDependencies-type - node: bundledDependencies - Type should be an Object
```

**Comment by tclindner** [comment]
Thank you @akihyro for catching this bug! I'll get a new version released today.

**Comment by tclindner** [comment]
Hi @akihyro v2.11.2 has been published. I've updated the docs too. Let me know if it doesn't meet your needs.

**Comment by akihyro** [comment]
It worked. Thank you 👍
