### ISSUE TITLE
Rules link is broken

### ISSUE THREAD

**Issue by AlekhyaYalla** [tclindner/npm-package-json-lint#734]
I've tried looking at rules, I could see the link is broken. 
<img width="1261" alt="image" src="https://user-images.githubusercontent.com/37897915/177737453-28d15a7f-7582-4a33-b7d7-3aaa0139b9ff.png">

**Comment by tclindner** [comment]
Hey @AlekhyaYalla can you please describe how you are navigating the site when you hit this 404 page? I see this - 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5178550/178158003-30b4a183-e01f-4b7c-bdc4-573f86aa1935.png">

I've also tried viewing specific rules.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5178550/178158025-700f9c30-76b7-451d-9435-45e359291808.png">
