### ISSUE TITLE
improvement: recursive config file detection

### ISSUE THREAD

**Issue by dnepro** [tclindner/npm-package-json-lint#75]
Hello everybody :)

It would also be really cool if the config file would be detected recursively upwards the file system, like for the `.eslintrc` and `.npmrc` files.

**Comment by tclindner** [comment]
Hi @dnepro, thank you again for using the project! I'll try to get to this soon.

**Comment by ntwb** [comment]
When I saw https://github.com/tclindner/npm-package-json-lint/wiki/configuration I thought this package would have been using https://www.npmjs.com/package/cosmiconfig for that, turns out it's not, I'd say it's worth checking out though as it supports traversing recursively up folders to find a valid config

**Comment by tclindner** [comment]
Hi @dnepro and @ntwb - a pre-release of v3.0.0 has been published to npm. The documentation is still a little sparse (that will change by the stable release). You can try it out by installing `npm-package-json-lint@beta`. Here is a link to the start of the [migration guide](https://github.com/tclindner/npm-package-json-lint/wiki/migrating-from-v2-to-v3). 

Configuration now does the following: 

1. Starts by looking for a `npmPackageJsonLintConfig` property in the current package.json file being linted.
2. Checks for a `.npmpackagejsonlintrc.json` file in the same directory as the current package.json file that is be linted. If that file doesn't exist, checks for a `npmpackagejsonlint.config.js` file. The same process is done for all parent directories in the project hierarchy until the root of the project is reached. Each successive level up the directory structure is used as the base config for the lower directory. You can avoid scanning parent directories by setting a `root` property in the config file with a value of `true`. The resulting config object from this scan is merged with the config object in step 1.
3. Config is loaded for the cli `configFile` option. This config object is merged with the final object from step 2.
4. If you are using the CLIEngine programmatically, you can pass an config object in the options. The object is merged with the result from step 3. If you are using the cli, this isn't applicable. 
5. If no config is found in steps 1-4, then the home directory is checked for a `.npmpackagejsonlintrc.json` file first and `npmpackagejsonlint.config.js` file if the first doesn't exist. If neither are found an exception is thrown saying no config can be found.

Let me know what you think!

**Comment by tclindner** [comment]
v3.0.0 has been released! 🎉
