### ISSUE TITLE
Feat: "script-type"

### ISSUE THREAD

**Issue by reggi** [tclindner/npm-package-json-lint#77]
Right now this validates valid cases where the individual script is not a string.

**Comment by reggi** [comment]
@tclindner That would be amazing!

**Comment by tclindner** [comment]
Hi @reggi - Can you please clarify what you are asking for with this request?

**Comment by reggi** [comment]
@tclindner This proposal is for `script-type`.


So `scripts-type` (note the s) exists which needs to be an object. For example.

This passes:

```json
{
   "scripts": {
       "hello": "echo hello"
   }
}
```

This fails.

```json
{
   "script": false
}
```

This feature request is for the following:

But I had an issue recently where a automatic script malfunctioned and added the entire package.json as a property of a `scripts`, and it passed into my CI / CD pipeline, causing mayhem.

I would like this to pass:

```json
 {
   "scripts": {
       "hello": "echo hello"
   }
}
```

I would like this to fail:

```json
{
   "scripts": {
       "hello":  {
           "hello": "echo hello"
       }
   }
}
```

and this as well

```json
{
   "scripts": {
       "hello":  true
   }
}
```
