### ISSUE TITLE
Add `valid-values-publishConfig` rule

### ISSUE THREAD

**Issue by ntwb** [tclindner/npm-package-json-lint#80]
I'd like to be able to enforce `"access": "public"` as the value for  `publishConfig`:

```json
	"publishConfig": {
		"access": "public"
	}
```

Currently [require-publishConfig](https://github.com/tclindner/npm-package-json-lint/wiki/require-publishConfig) requires that `publishConfig` exists

**Comment by tclindner** [comment]
I’ll get this tweaked later today. v3 docs are nearly done, so I should have them out later today too! 🎉

**Comment by tclindner** [comment]
Hey @ntwb - `valid-values-publishConfig` has been published to the beta package for v3. Here is a link to the [docs](https://github.com/tclindner/npm-package-json-lint/wiki/valid-values-publishConfig). Let me know what you think.
