### ISSUE TITLE
New Rule: Indentation Validation

### ISSUE THREAD

**Issue by ntwb** [tclindner/npm-package-json-lint#81]
It would be great to have an _indentation_ rule.

Our repo uses _tabs_ for indentation in all JSON files including `package.json` 

(npm added/fixed support for _tabbed_ indentaion in the 5.x releases)

Turns out, whilst creating our npm-package-json-lint _shared config_ I used _spaces_ instead of _tabs_ 🤦‍♂️ 

Having a rule to detect, and enforce the correct indentation type would be awesome

ESLint use this configuration for their [indent](https://eslint.org/docs/4.0.0/rules/indent#options) rule:

> For example, for 2-space indentation:
```
{
    "indent": ["error", 2]
}
```

Or for tabbed indentation:
```
{
    "indent": ["error", "tab"]
}
```

<img src="https://media1.giphy.com/media/l0IylSajlbPRFxH8Y/giphy.gif">

**Comment by tclindner** [comment]
Great suggestion, @ntwb! I love the gif 😂 🙈

**Comment by ntwb** [comment]
Closing per discussion in that parsing JSON to an AST doesn't have many good options right now
