### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by aduth** [tclindner/npm-package-json-lint#91]
In Windows environments, the following error is thrown:

```
 "wp-scripts lint-pkg-json" found some errors. Please fix them and try committing again.
Pattern, [...]\plugins\gutenberg\packages\wordcount\package.json, is a file, but isn't a package.json file.
```

Looking at the source for where the error is thrown, it's expected this could be an issue with the path separator differences in Windows environments:

https://github.com/tclindner/npm-package-json-lint/blob/ca25109a1e48e6eb3333ca313de11e1a9a26a62b/src/CLIEngine.js#L181

See also:

- https://nodejs.org/api/path.html#path_path_sep
- https://nodejs.org/api/path.html#path_path_join_paths

Context:

- [Discussed in WordPress Make Slack instance](https://wordpress.slack.com/archives/C02QB2JS7/p1534858929000100), as it is effecting development of [WordPress/gutenberg](https://github.com/WordPress/gutenberg/) (chat link [requires registration](https://make.wordpress.org/chat/))
- npm-package-json-lint version: 3.3.0
- npm version: Unknown (relaying from original reporter)
- node version: Unknown (relaying from original reporter) 

Our configuration, including defined dependency links, can be found at https://github.com/WordPress/gutenberg/tree/master/packages/npm-package-json-lint-config

**Comment by tclindner** [comment]
Sorry about that! I’ll get a fix push later today.

**Comment by tclindner** [comment]
Thank you so much for the detailed issue description, @aduth!

**Comment by aduth** [comment]
Thanks @tclindner . Will give it a shot and report back if we have any issues 👍
