### ISSUE TITLE
feature suggestion: support exceptions for the "prefer-...-dependencies" rules

### ISSUE THREAD

**Issue by lddubeau** [tclindner/npm-package-json-lint#93]
I use rules like `prefer-caret-version-dependencies`. However, sometimes a dependency has a problem that requires me to specify a version range that cannot be represented with a caret version.

Looking at the documentation, I cannot see a way currently to specify exceptions to the rule. Either all dependencies are checked and if any of them don't use the caret syntax, I get an error. Or I have to turn off the rule or make it a warning. But a warning is not really the level of forcefulness I want. It is too easy to miss a warning.

**Comment by tclindner** [comment]
Great suggestion, @lddubeau!

**Comment by ntwb** [comment]
I just went searching the repo here for "exception", I've a use case in the monorepo we use @WordPress where 20 of the packages require `require-module`, and the other 20 do not.

So thinking on a wider note, there would be a use case for many of the rules in this package to allow exceptions of some sort.

**Comment by tclindner** [comment]
@ntwb - I'm curious if you would prefer this for your monorepo scenario.
Use globs to specify different config for sub-packages (note the draft structure below is a breaking change. I'm not sure about this syntax 🤓. I'm curious where some for the RFCs for ESLint will go in 2019). 

The linter would use the first config object for the root package.json file. The linter would use the second config object package.json files in the submodules directory. 

```
[
  {
    "files": ["package.json"],
    "rules": {
      "require-module": "error"
    }
  },
  {
    "files": ["submodules/**/package.json"],
    "rules": {
      "require-module": "off"
    }
  }
]
```

@lddubeau - is your scenario more like this? Exceptions to rules where, for example, `prefer-caret-version-dependencies` is set but it doesn't check packages listed in an array of exceptions. 

```
{
  "rules": {
    "prefer-caret-version-dependencies": ["error", {
      "exceptions": ["moduleToIgnore"]
    }]
  }
}
```

**Comment by lddubeau** [comment]
@tclindner Yep, within the same `package.json` the rule should generally apply but some modules should be ignored by the rule. Adding an `exceptions` field to configure the rule would do it.

**Comment by ntwb** [comment]
Thanks @tclindner looking at the file glob example:

> ` "files": ["submodules/**/package.json"],`

I think having a glob pattern for ~20 paths, i.e. I want to exclude ~20 from the ~40 we have might get a little unwieldy.

Whereas, your second example with an array of modules to exclude I think looks a little cleaner:

```
{
  "rules": {
    "prefer-caret-version-dependencies": ["error", {
      "exceptions": [
		"moduleToIgnore1",
		"moduleToIgnore2",
		"moduleToIgnore3",
		]
    }]
  }
}
```
