### ISSUE TITLE
Support overrides

### ISSUE THREAD

**Issue by jogold** [tclindner/npm-package-json-lint#96]
It would be great to have support for an `overrides` field in the config file, just like `ESLint` has. This could be especially useful for monorepos.

```json
{
  "overrides": {
    "files": ["./package.json", "./packages/package1/package.json"],
    "rules": {
      "require-homepage": "off"
    }
  }
}
```

Any plans to support this? Ready to help.

**Comment by tclindner** [comment]
Hey @jogold! Thank you for using the project. We have a version of this right now. If you are using a monorepo you can place different config for each project in the repo. npm-package-json-lint will check the config for each project and lint them according to those rules. It is also possible to cascade the config too. For example, if you place the main config in the root of the repo then separate config in a sub-directory the config from the sub-directory will be merged with the config from the root. Do you think that will meet your needs? If not, I would love to add override functionality and would welcome your help 😄

**Comment by jogold** [comment]
Hi @tclindner,

Thanks for the detailed answer. I'm currently using this "merge" functionality but it doesn't cover all cases. 

Let's say I'm using an `extends` in the root `package.json` with all the rules that should be applied to the majority of my packages in `packages/`. If I want to disable a rule in one of my packages I can go to the `package.json` of this package and add a `npmPackageJsonLintConfig` in there. But if I want to disable a  rule for the root `package.json`, I don't see any practical way of doing it.

**Comment by tclindner** [comment]
Hey @jogold would you be willing to help with this for v4?

**Comment by jogold** [comment]
Hey @tclindner, thanks for reaching out!

I don't have a lot of time right now... keep you posted.

**Comment by tclindner** [comment]
No worries, @jogold! Good luck with your projects 🥇
