### ISSUE TITLE
Support `--ignore-path` for CLI

### ISSUE THREAD

**Issue by evilebottnawi** [tclindner/npm-package-json-lint#99]
I remove template because it is not bug, it is feature. stylelint/eslint/etc linters have `--ignore-path` CLI option for ignoring paths, example i have project where use `php` and `nodejs`, `php` use `composer` as package manager and store all dependencies in `vendor` directory and some packages contains `package.json`, i want ignore `vendor` directory.

I use `npmPkgJsonLint --quiet .` command for linting.

Also it is speedup glob (and linting too), because repo can contains a lot of directory and files which are not included in git. Will be great support `npmPkgJsonLint --quiet . --ignore-path .gitignore`. I can send a PR.

**Comment by tclindner** [comment]
Great suggestion, @evilebottnawi! I would love a PR if you have time. Thank you 🥇
